const remoteMemoryChips = [
    {"partNumber":"V53C408H","manufacturer":"Mosel","organization":"1Mx4","type":"EDO","density":"512K","refresh":"1K","voltage":"5V"},
    {"partNumber":"HY5117404B","manufacturer":"Hyundai","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
    {"partNumber":"HY5116404B","manufacturer":"Hyundai","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"4K","voltage":"5V"},
	{"partNumber":"HY51V16404A","manufacturer":"Hyundai","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HY51V17404A","manufacturer":"Hyundai","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"3.3V"},
	{"partNumber":"UPD4217405","manufacturer":"NEC","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"VG2617405FJ","manufacturer":"VIS","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"VG26V17405FJ","manufacturer":"VIS","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"3.3V"},
	{"partNumber":"VG26S17405FJ","manufacturer":"VIS","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"VG26VS17405FJ","manufacturer":"VIS","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"3.3V"},
	{"partNumber":"VG2617400D","manufacturer":"VIS","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"VG26V17400D","manufacturer":"VIS","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"3.3V"},
	{"partNumber":"VG26S17400D","manufacturer":"VIS","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"VG26VS17400D","manufacturer":"VIS","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"3.3V"},
	{"partNumber":"NT511740C5J","manufacturer":"Nanya","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"TMS4C1024","manufacturer":"TI","organization":"1Mx1","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TMS45160","manufacturer":"TI","organization":"256Kx16","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TMS44C256","manufacturer":"TI","organization":"256Kx4","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TMS44400","manufacturer":"TI","organization":"1Mx4","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TMS44100","manufacturer":"TI","organization":"4Mx1","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TMS4256","manufacturer":"TI","organization":"256Kx1","type":"FPM","density":"32KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TMS418169","manufacturer":"TI","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"TMS418160","manufacturer":"TI","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"TMS417809","manufacturer":"TI","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"TMS417800","manufacturer":"TI","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"TMS417400","manufacturer":"TI","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"TMS416400","manufacturer":"TI","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TMS416160","manufacturer":"TI","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TMS416100","manufacturer":"TI","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TCTC514400","manufacturer":"Toshiba","organization":"1Mx4","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TC514800","manufacturer":"Toshiba","organization":"512Kx8","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TC514260","manufacturer":"Toshiba","organization":"256Kx16","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TC514256","manufacturer":"Toshiba","organization":"256Kx4","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TC514100","manufacturer":"Toshiba","organization":"4Mx1","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TC5118165","manufacturer":"Toshiba","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"TC5118160","manufacturer":"Toshiba","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"TC5118160","manufacturer":"Toshiba","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TC5117805","manufacturer":"Toshiba","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"TC5117800","manufacturer":"Toshiba","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"TC5117405","manufacturer":"Toshiba","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"TC5117400","manufacturer":"Toshiba","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"TC5117400","manufacturer":"Toshiba","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TC5116400","manufacturer":"Toshiba","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TC5116160","manufacturer":"Toshiba","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TC5116100","manufacturer":"Toshiba","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"4K","voltage":"5V"},
	{"partNumber":"TC5116100","manufacturer":"Toshiba","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TC511000","manufacturer":"Toshiba","organization":"1Mx1","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TC41256","manufacturer":"Toshiba","organization":"256Kx1","type":"FPM","density":"32KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MT4LC1M16C3","manufacturer":"Micron","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MT4C8512","manufacturer":"Micron","organization":"512Kx8","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MT4C4M4E8","manufacturer":"Micron","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MT4C4M4B1","manufacturer":"Micron","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MT4C4M4","manufacturer":"Micron","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MT4C4256","manufacturer":"Micron","organization":"256Kx4","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MT4C4001","manufacturer":"Micron","organization":"1Mx4","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MT4C2M8E7","manufacturer":"Micron","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MT4C2M8B1","manufacturer":"Micron","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MT4C1M16E5","manufacturer":"Micron","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"MT4C1M16C3","manufacturer":"Micron","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"MT4C16M1","manufacturer":"Micron","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MT4C16257","manufacturer":"Micron","organization":"256Kx16","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MT4C1024","manufacturer":"Micron","organization":"1Mx1","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MT4C1004","manufacturer":"Micron","organization":"4Mx1","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MT1256","manufacturer":"Micron","organization":"256Kx1","type":"EDO","density":"32KB","refresh":"4K","voltage":"5V"},
	{"partNumber":"GM71C16401","manufacturer":"Goldstar","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"GM71C17100","manufacturer":"Goldstar","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"GM71C17400","manufacturer":"Goldstar","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"GM71C17401","manufacturer":"Goldstar","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"GM71C17403","manufacturer":"Goldstar","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"GM71C17800","manufacturer":"Goldstar","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"GM71C17803","manufacturer":"Goldstar","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"GM71C18160","manufacturer":"Goldstar","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"GM71C18163","manufacturer":"Goldstar","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"GM71C256","manufacturer":"Goldstar","organization":"256Kx1","type":"EDO","density":"32KB","refresh":"4K","voltage":"5V"},
	{"partNumber":"GM71C4100","manufacturer":"Goldstar","organization":"4Mx1","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"GM71C4256","manufacturer":"Goldstar","organization":"256Kx4","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"GM71C4260","manufacturer":"Goldstar","organization":"256Kx16","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"GM71C4400","manufacturer":"Goldstar","organization":"1Mx4","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"GM71C4800","manufacturer":"Goldstar","organization":"512Kx8","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"TMS417409","manufacturer":"TI","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"HIT5116100","manufacturer":"Hitachi","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"4K","voltage":"5V"},
	{"partNumber":"HIT5117400","manufacturer":"Hitachi","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"HIT5117405","manufacturer":"Hitachi","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"HIT5117800","manufacturer":"Hitachi","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"HIT5117805","manufacturer":"Hitachi","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"HIT5118160","manufacturer":"Hitachi","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"HIT5118165","manufacturer":"Hitachi","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"HM511000","manufacturer":"Hitachi","organization":"1Mx1","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HM5116100","manufacturer":"Hitachi","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HM5116160","manufacturer":"Hitachi","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HM5116400","manufacturer":"Hitachi","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HM5118160","manufacturer":"Hitachi","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HM51256","manufacturer":"Hitachi","organization":"256Kx1","type":"EDO","density":"32KB","refresh":"4K","voltage":"5V"},
	{"partNumber":"HM514100","manufacturer":"Hitachi","organization":"4Mx1","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HM514256","manufacturer":"Hitachi","organization":"256Kx4","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HM514260","manufacturer":"Hitachi","organization":"256Kx16","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HM514400","manufacturer":"Hitachi","organization":"1Mx4","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HM514800","manufacturer":"Hitachi","organization":"512Kx8","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HY5116100","manufacturer":"Hyundai","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HY5116100","manufacturer":"Hyundai","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"4K","voltage":"5V"},
	{"partNumber":"HY5116160","manufacturer":"Hyundai","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HY5116400","manufacturer":"Hyundai","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HY5117400","manufacturer":"Hyundai","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"HY5117405","manufacturer":"Hyundai","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"HY5117800","manufacturer":"Hyundai","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"HY5117805","manufacturer":"Hyundai","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"HY5118160","manufacturer":"Hyundai","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HY5118160","manufacturer":"Hyundai","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"HY5118164","manufacturer":"Hyundai","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"HY514100","manufacturer":"Hyundai","organization":"4Mx1","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HY514260","manufacturer":"Hyundai","organization":"256Kx16","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HY514400","manufacturer":"Hyundai","organization":"1Mx4","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HY514800","manufacturer":"Hyundai","organization":"512Kx8","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HY531000","manufacturer":"Hyundai","organization":"1Mx1","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HY534256","manufacturer":"Hyundai","organization":"256Kx4","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"HY53C256","manufacturer":"Hyundai","organization":"256Kx1","type":"EDO","density":"32KB","refresh":"4K","voltage":"5V"},
	{"partNumber":"5117400","manufacturer":"Siemens/Infineon","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"5117405","manufacturer":"Siemens/Infineon","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"5117800","manufacturer":"Siemens/Infineon","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"5117805","manufacturer":"Siemens/Infineon","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"5118160","manufacturer":"Siemens/Infineon","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"5118165","manufacturer":"Siemens/Infineon","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"K41C16000","manufacturer":"Samsung","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"4K","voltage":"5V"},
	{"partNumber":"K4E151611","manufacturer":"Samsung","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"K4E160411","manufacturer":"Samsung","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"K4E160811","manufacturer":"Samsung","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"K4F151611","manufacturer":"Samsung","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"K4F160411","manufacturer":"Samsung","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"K4F160811","manufacturer":"Samsung","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"KM41256","manufacturer":"Samsung","organization":"256Kx1","type":"FPM","density":"32KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"KM416C1000","manufacturer":"Samsung","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"KM416C1200","manufacturer":"Samsung","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"KM416C1204","manufacturer":"Samsung","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"KM416C256","manufacturer":"Samsung","organization":"256Kx16","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"KM41C1000","manufacturer":"Samsung","organization":"1Mx1","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"KM41C16000","manufacturer":"Samsung","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"KM41C16000","manufacturer":"Samsung","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"4K","voltage":"5V"},
	{"partNumber":"KM41C16100","manufacturer":"Samsung","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"KM41C4000","manufacturer":"Samsung","organization":"4Mx1","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"KM44C1000","manufacturer":"Samsung","organization":"1Mx4","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"KM44C256","manufacturer":"Samsung","organization":"256Kx4","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"KM44C4000","manufacturer":"Samsung","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"KM44C4100","manufacturer":"Samsung","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"KM44C4100","manufacturer":"Samsung","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"KM44C4104","manufacturer":"Samsung","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"KM48C2100","manufacturer":"Samsung","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"KM48C2104","manufacturer":"Samsung","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"KM48C512","manufacturer":"Samsung","organization":"512Kx8","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"M5M41000","manufacturer":"Mitsubishi","organization":"1Mx1","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"M5M416100","manufacturer":"Mitsubishi","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"M5M416100","manufacturer":"Mitsubishi","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"4K","voltage":"5V"},
	{"partNumber":"M5M416160","manufacturer":"Mitsubishi","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"M5M416400","manufacturer":"Mitsubishi","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"M5M417400","manufacturer":"Mitsubishi","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"M5M417409","manufacturer":"Mitsubishi","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"M5M417800","manufacturer":"Mitsubishi","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"M5M417805","manufacturer":"Mitsubishi","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"M5M418160","manufacturer":"Mitsubishi","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"M5M418160","manufacturer":"Mitsubishi","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"M5M418165","manufacturer":"Mitsubishi","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"M5M4256","manufacturer":"Mitsubishi","organization":"256Kx1","type":"EDO","density":"32KB","refresh":"4K","voltage":"5V"},
	{"partNumber":"M5M44100","manufacturer":"Mitsubishi","organization":"4Mx1","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"M5M44256","manufacturer":"Mitsubishi","organization":"256Kx4","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"M5M44260","manufacturer":"Mitsubishi","organization":"256Kx16","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"M5M44400","manufacturer":"Mitsubishi","organization":"1Mx4","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"M5M44800","manufacturer":"Mitsubishi","organization":"512Kx8","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MB8116100","manufacturer":"Fujitsu","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MB8116100","manufacturer":"Fujitsu","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"4K","voltage":"5V"},
	{"partNumber":"MB8116160","manufacturer":"Fujitsu","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MB8116400","manufacturer":"Fujitsu","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MB8117400","manufacturer":"Fujitsu","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MB8117405","manufacturer":"Fujitsu","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MB8117800","manufacturer":"Fujitsu","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MB8117805","manufacturer":"Fujitsu","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MB8118160","manufacturer":"Fujitsu","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"MB8118165","manufacturer":"Fujitsu","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"MB81256","manufacturer":"Fujitsu","organization":"256Kx1","type":"EDO","density":"32KB","refresh":"4K","voltage":"5V"},
	{"partNumber":"MB814100","manufacturer":"Fujitsu","organization":"4Mx1","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MB814260","manufacturer":"Fujitsu","organization":"256Kx16","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MB814400","manufacturer":"Fujitsu","organization":"1Mx4","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MB814800","manufacturer":"Fujitsu","organization":"512Kx8","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MB81C1000","manufacturer":"Fujitsu","organization":"1Mx1","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MB81C4256","manufacturer":"Fujitsu","organization":"256Kx4","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM511000","manufacturer":"Motorola","organization":"1Mx1","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM514100","manufacturer":"Motorola","organization":"4Mx1","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM514256","manufacturer":"Motorola","organization":"256Kx4","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM514400","manufacturer":"Motorola","organization":"1Mx4","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM516100","manufacturer":"Motorola","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM516160","manufacturer":"Motorola","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM516400","manufacturer":"Motorola","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM517400","manufacturer":"Motorola","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM518160","manufacturer":"Motorola","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM54260","manufacturer":"Motorola","organization":"256Kx16","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM54800","manufacturer":"Motorola","organization":"512Kx8","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MCM6256","manufacturer":"Motorola","organization":"256Kx1","type":"FPM","density":"32KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM41256","manufacturer":"OKI","organization":"256Kx1","type":"FPM","density":"32KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM511000","manufacturer":"OKI","organization":"1Mx1","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM5116100","manufacturer":"OKI","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM5116100","manufacturer":"OKI","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"4K","voltage":"5V"},
	{"partNumber":"MSM5116160","manufacturer":"OKI","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM5116400","manufacturer":"OKI","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM5117100","manufacturer":"OKI","organization":"16Mx1","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM5117400","manufacturer":"OKI","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM5117400","manufacturer":"OKI","organization":"4Mx4","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MSM5117405","manufacturer":"OKI","organization":"4Mx4","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MSM5117800","manufacturer":"OKI","organization":"2Mx8","type":"FPM","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MSM5117805","manufacturer":"OKI","organization":"2Mx8","type":"EDO","density":"2MB","refresh":"2K","voltage":"5V"},
	{"partNumber":"MSM5118160","manufacturer":"OKI","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM5118160","manufacturer":"OKI","organization":"1Mx16","type":"FPM","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"MSM5118165","manufacturer":"OKI","organization":"1Mx16","type":"EDO","density":"2MB","refresh":"1K","voltage":"5V"},
	{"partNumber":"MSM514100","manufacturer":"OKI","organization":"4Mx1","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM514256","manufacturer":"OKI","organization":"256Kx4","type":"FPM","density":"128KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM514260","manufacturer":"OKI","organization":"256Kx16","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM514400","manufacturer":"OKI","organization":"1Mx4","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MSM514800","manufacturer":"OKI","organization":"512Kx8","type":"FPM","density":"512KB","refresh":"(not set)","voltage":"5V"},
	{"partNumber":"MT4LC16M4A7","manufacturer":"Micron","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MT4LC16M4G3","manufacturer":"Micron","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MT4LC16M4H9","manufacturer":"Micron","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MT4LC16M4T8","manufacturer":"Micron","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MT4LC4M16F5","manufacturer":"Micron","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MT4LC4M16R6","manufacturer":"Micron","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MT4LC8M8B6","manufacturer":"Micron","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MT4LC8M8C2","manufacturer":"Micron","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"UPD4264160","manufacturer":"NEC","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MT4LC8M8E1","manufacturer":"Micron","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"UPD4264165","manufacturer":"NEC","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MT4LC8M8P4","manufacturer":"Micron","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"UPD4264400","manufacturer":"NEC","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"UPD4264405","manufacturer":"NEC","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"UPD4264800","manufacturer":"NEC","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"UPD4264805","manufacturer":"NEC","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"UPD4265160","manufacturer":"NEC","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"UPD4265165","manufacturer":"NEC","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"UPD4265400","manufacturer":"NEC","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"UPD4265405","manufacturer":"NEC","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"UPD4265800","manufacturer":"NEC","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"UPD4265805","manufacturer":"NEC","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"TC5164400","manufacturer":"Toshiba","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"TC5164405","manufacturer":"Toshiba","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"TC5164800","manufacturer":"Toshiba","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"TC5164805","manufacturer":"Toshiba","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"TC5165400","manufacturer":"Toshiba","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"TC5165800","manufacturer":"Toshiba","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"TC5165805","manufacturer":"Toshiba","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"GM71V64400","manufacturer":"Goldstar","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"GM71V64404","manufacturer":"Goldstar","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"GM71V64804","manufacturer":"Goldstar","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"GM71V65160","manufacturer":"Goldstar","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"GM71V65163","manufacturer":"Goldstar","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"GM71V65400","manufacturer":"Goldstar","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"GM71V65404","manufacturer":"Goldstar","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"GM71V65804","manufacturer":"Goldstar","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"TMS464400","manufacturer":"TI","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"TMS464409","manufacturer":"TI","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"TMS464800","manufacturer":"TI","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"TMS464809","manufacturer":"TI","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HIT5164160","manufacturer":"Hitachi","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"TMS465400","manufacturer":"TI","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HIT5164165","manufacturer":"Hitachi","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"TMS465800","manufacturer":"TI","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HIT5164400","manufacturer":"Hitachi","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"TMS465809","manufacturer":"TI","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HIT5164405","manufacturer":"Hitachi","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HIT5164800","manufacturer":"Hitachi","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HIT5164805","manufacturer":"Hitachi","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HIT5165160","manufacturer":"Hitachi","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HIT5165165","manufacturer":"Hitachi","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HIT5165400","manufacturer":"Hitachi","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HIT5165405","manufacturer":"Hitachi","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HIT5165800","manufacturer":"Hitachi","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HIT5165805","manufacturer":"Hitachi","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HY51V64160","manufacturer":"Hyundai","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HY51V64164","manufacturer":"Hyundai","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HY51V64400","manufacturer":"Hyundai","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HY51V64404","manufacturer":"Hyundai","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HY51V64800","manufacturer":"Hyundai","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HY51V64804","manufacturer":"Hyundai","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HY51V65160","manufacturer":"Hyundai","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HY51V65164","manufacturer":"Hyundai","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HY51V65400","manufacturer":"Hyundai","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HY51V65404","manufacturer":"Hyundai","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HY51V65800","manufacturer":"Hyundai","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HY51V65804","manufacturer":"Hyundai","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HYB3164400","manufacturer":"Siemens/Infineon","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HYB3164405","manufacturer":"Siemens/Infineon","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HYB3164805","manufacturer":"Siemens/Infineon","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"HYB3165400","manufacturer":"Siemens/Infineon","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HYB3165805","manufacturer":"Siemens/Infineon","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"HYB3165805","manufacturer":"Siemens/Infineon","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"K4E640812","manufacturer":"Samsung","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"K4E660412","manufacturer":"Samsung","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"K4E660812","manufacturer":"Samsung","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"K4F640412","manufacturer":"Samsung","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"K4F640812","manufacturer":"Samsung","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"K4F660412","manufacturer":"Samsung","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"K4F660812","manufacturer":"Samsung","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"KM44V16000","manufacturer":"Samsung","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"KM44V16004","manufacturer":"Samsung","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"KM44V16100","manufacturer":"Samsung","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"KM48V8000","manufacturer":"Samsung","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"KM48V8004","manufacturer":"Samsung","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"KM48V8100","manufacturer":"Samsung","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"KM48V8104","manufacturer":"Samsung","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"M5M465160","manufacturer":"Mitsubishi","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"M5M465165","manufacturer":"Mitsubishi","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"M5M465400","manufacturer":"Mitsubishi","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"M5M465405","manufacturer":"Mitsubishi","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"M5M465800","manufacturer":"Mitsubishi","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"M5M465805","manufacturer":"Mitsubishi","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"M5M467160","manufacturer":"Mitsubishi","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"M5M467165","manufacturer":"Mitsubishi","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"M5M467400","manufacturer":"Mitsubishi","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"M5M467405","manufacturer":"Mitsubishi","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"M5M467800","manufacturer":"Mitsubishi","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"M5M467805","manufacturer":"Mitsubishi","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MB81V16160","manufacturer":"Fujitsu","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MB81V16165","manufacturer":"Fujitsu","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MB81V16400","manufacturer":"Fujitsu","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MB81V16405","manufacturer":"Fujitsu","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MB81V16800","manufacturer":"Fujitsu","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MB81V16805","manufacturer":"Fujitsu","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MB81V18160","manufacturer":"Fujitsu","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MB81V18165","manufacturer":"Fujitsu","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MB81V4400","manufacturer":"Fujitsu","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MB81V4800","manufacturer":"Fujitsu","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MB81V4805","manufacturer":"Fujitsu","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM5164400","manufacturer":"OKI","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MSM5164405","manufacturer":"OKI","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MSM5164800","manufacturer":"OKI","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MSM5164805","manufacturer":"OKI","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MSM5165160","manufacturer":"OKI","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM5165165","manufacturer":"OKI","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM5165400","manufacturer":"OKI","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM5165405","manufacturer":"OKI","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM5165800","manufacturer":"OKI","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM5165805","manufacturer":"OKI","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM51V16400","manufacturer":"OKI","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MSM51V16405","manufacturer":"OKI","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MSM51V16800","manufacturer":"OKI","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MSM51V16805","manufacturer":"OKI","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MSM51V17400","manufacturer":"OKI","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM51V17405","manufacturer":"OKI","organization":"16Mx4","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM51V17800","manufacturer":"OKI","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM51V17805","manufacturer":"OKI","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM51V18160","manufacturer":"OKI","organization":"4Mx16","type":"FPM","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM51V18165","manufacturer":"OKI","organization":"4Mx16","type":"EDO","density":"8MB","refresh":"4K","voltage":"3.3V"},
	{"partNumber":"MSM51V4400","manufacturer":"OKI","organization":"16Mx4","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MSM51V4800","manufacturer":"OKI","organization":"8Mx8","type":"FPM","density":"8MB","refresh":"8K","voltage":"3.3V"},
	{"partNumber":"MSM51V4805","manufacturer":"OKI","organization":"8Mx8","type":"EDO","density":"8MB","refresh":"8K","voltage":"3.3V"}
];